import Head from 'next/head'
import About from '../components/about'
import Main from '../components/main'

import Navbar from '../components/navbar'
import Project from '../components/project'
import Skills from '../components/skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Güncel || Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
      <Project/>
    </div>
  )
}
